# this is example. you must replace ccid and keys before deploy.

server:
  dsn: "host=db user=postgres password=postgres dbname=concurrent port=5432 sslmode=disable"
  redisAddr: "redis:6379"
  traceEndpoint: "localhost:4318"
  enableTrace: false
  logpath: "" # empty for default(/var/log/concurrent)
  captchaSitekey: "6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI" # !! this is test sitekey !!
  captchaSecret: "6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe"  # !! this is test secret !!

concurrent:
  # fqdn is instance ID
  # It is really hard and not recommended to change this value after node started
  fqdn: changeme.example.tld
  # 'open' or 'invite' or 'close'
  registration: open
  # server agent account
  # it is handy to generate these info with concurrent.world devtool
  ccid: CCxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  publickey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  privatekey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

profile:
  nickname: concurrent-domain
  description: domain description
  logo: ''
  wordmark: ''
  themeColor: '#20193b'
  rules: |
    - 他のユーザーにリスペクトを持って接しましょう
      Treat everyone with respect
    - スパムは禁止です
      No spamming
    - 攻撃的なプロフィール名・画像はやめましょう
      No offensive names and profile pictures
  tosURL: ''
  maintainerName: notset
  maintainerEmail: notset@example.com

