# this is example. you must replace ccid and keys before deploy.

server:
  dsn: "host=db user=postgres password=postgres dbname=concurrent port=5432 sslmode=disable"
  redisAddr: "redis:6379"
  memcachedAddr: "memcached:11211"
  traceEndpoint: "localhost:4318"
  enableTrace: false
  logpath: "" # empty for default(/var/log/concurrent)
  captchaSitekey: "6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"
  captchaSecret: "6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe"

concurrent:
  # fqdn is instance ID
  # It is really hard and not recommended to change this value after node started
  fqdn: example.tld
  # 'open' or 'invite' or 'close'
  registration: open
  # server agent account
  # it is handy to generate these info with concurrent.world devtool
  dimension: concrnt-mainnet
  privatekey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

profile:
  nickname: concurrent-domain
  description: domain description
  logo: 'https://concurrent.world/concurrent.png'
  wordmark: ''
  themeColor: '#20193b'
  maintainerName: notset
  maintainerEmail: notset@example.com

